# Generated by Django 5.2.5 on 2025-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogc', '0002_blogcategory_remove_post_category_remove_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', max_length=20),
        ),
    ]
