# Generated by Django 5.2.5 on 2025-08-24 14:06

import blogc.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogc', '0005_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=blogc.storage_backends.MediaStorage(), upload_to='post_images/'),
        ),
    ]
